platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'NXLTools' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'Toast'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'SDCycleScrollView'
pod 'CYLTabBarController'
pod 'YPTabBarController'
pod 'XHLaunchAd'
pod 'WebViewJavascriptBridge'
pod 'JLRoutes'
pod 'YYKit'
pod 'FMDB'
#pod 'Realm'
pod 'SAMKeychain'
#pod 'DWScrollPictures', '1.0.7'
pod 'Bugly'
pod 'SMSSDK'
pod 'pop'

end
